/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class AdminManageSystem_114 extends javax.swing.JFrame {

   /**
     * Creates new form AdminManageUser_111
     */
    String [] a;
    String str;
    Statement stmt;
    Connection con=DBClass.getConnection();//连接数据库
    ResultSet rs;
    DefaultTableModel tm;
    PreparedStatement preparedStatement;
    PreparedStatement pst1,pst2,pst3,pst4;
    ChangePassword_121 cp =new ChangePassword_121();
    public AdminManageSystem_114() {
        initComponents();
        thaw.setVisible(false);
        this.setDefaultCloseOperation(0x1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        freeze_users = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        thaw = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        searchusertxt = new javax.swing.JTextField();
        searchuser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        freeze = new javax.swing.JButton();
        StatusReset = new javax.swing.JButton();
        thawExit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System maganemnt");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, -1, -1));

        freeze_users.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        freeze_users.setText(" Freeze user");
        freeze_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freeze_usersMouseClicked(evt);
            }
        });
        getContentPane().add(freeze_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        change.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        change.setText("Change the password");
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
        });
        getContentPane().add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel2.setText("System Management");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, 390, 84));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 20, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/HUNI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 190));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        thaw.setOpaque(false);
        thaw.setLayout(null);

        jLabel17.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel17.setText("Thaw the users");
        thaw.add(jLabel17);
        jLabel17.setBounds(230, 20, 176, 28);

        jLabel18.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel18.setText("User ID ");
        thaw.add(jLabel18);
        jLabel18.setBounds(100, 60, 80, 20);

        searchusertxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        searchusertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchusertxtActionPerformed(evt);
            }
        });
        thaw.add(searchusertxt);
        searchusertxt.setBounds(190, 53, 310, 41);

        searchuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/search2.png"))); // NOI18N
        searchuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchuserMouseClicked(evt);
            }
        });
        thaw.add(searchuser);
        searchuser.setBounds(510, 50, 66, 40);

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "User Number", "User Name", "Tele", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usertable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(usertable);

        thaw.add(jScrollPane2);
        jScrollPane2.setBounds(170, 137, 386, 60);

        freeze.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        freeze.setText("Freeze");
        freeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                freezeMouseClicked(evt);
            }
        });
        freeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeActionPerformed(evt);
            }
        });
        thaw.add(freeze);
        freeze.setBounds(130, 230, 100, 31);

        StatusReset.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        StatusReset.setText("Reset");
        StatusReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatusResetMouseClicked(evt);
            }
        });
        StatusReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusResetActionPerformed(evt);
            }
        });
        thaw.add(StatusReset);
        StatusReset.setBounds(300, 230, 100, 31);

        thawExit.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        thawExit.setText("Exit");
        thawExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thawExitMouseClicked(evt);
            }
        });
        thaw.add(thawExit);
        thawExit.setBounds(490, 230, 90, 31);

        getContentPane().add(thaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 650, 270));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 810, 30));

        exit.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("Back");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/背景（几何）1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1120, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchusertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchusertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchusertxtActionPerformed

    private void searchuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchuserMouseClicked
        // TODO add your handling code here:
        try{
                String sql;
                sql = "select * from userdata where id=?";
                pst1 = con.prepareStatement(sql);
                pst1.setString(1, this.searchusertxt.getText());
                rs = pst1.executeQuery();//执行语句
                ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
		int ColumnCount = rsmd.getColumnCount();//获取表格列数
                tm = (DefaultTableModel)usertable.getModel();//建立表格模型，editbooktable表格变量名
                tm.setRowCount(0);//更新行数据，使表格清空
		while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
		{
                    for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                            {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                                a=new String[ColumnCount];//获取列头名字
                                for (int s =0; s < ColumnCount; s++)//小于行循环
                                {
					a[s]=rs.getString(s+1);//获取列数据
				}
                            }
			tm.addRow(a);//将行和列的数据整合，进行输出
			}
                        //当文本字段为空时弹出Warning窗口
                        if(searchusertxt.getText().length()==0)
                        {
                            JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                        }
                        tm.fireTableDataChanged();
//                        rs.close();
//                        stmt.close();
//                        con.close();//关闭
		}
		catch (SQLException e) {
                   JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
                  }//数据库报错
                catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
                }//整体报错
    }//GEN-LAST:event_searchuserMouseClicked

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
                cp.setLocationRelativeTo(null);
                cp.setVisible(true);
    }//GEN-LAST:event_changeMouseClicked

    private void freeze_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeze_usersMouseClicked
             thaw.setVisible(true); 
    }//GEN-LAST:event_freeze_usersMouseClicked

    private void freezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freezeMouseClicked
      
    }//GEN-LAST:event_freezeMouseClicked

    private void thawExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thawExitMouseClicked
        // TODO add your handling code here:
            thaw.setVisible(false);
    }//GEN-LAST:event_thawExitMouseClicked

    private void StatusResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusResetMouseClicked

    private void StatusResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusResetActionPerformed
        // TODO add your handling code here:
        try {
            if(searchusertxt.getText().length()==0){
                JOptionPane.showMessageDialog(this, "Please enter User ID first!","Warning",JOptionPane.WARNING_MESSAGE);
            }else{
                String sql = "update userdata set state='Normal' where id=?";
                pst2= con.prepareStatement(sql);
                pst2.setString(1,searchusertxt.getText());
                pst2.executeUpdate();//执行语句
                JOptionPane.showMessageDialog(this, "Execute Successfully!","Reset",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminManageSystem_114.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StatusResetActionPerformed

    private void freezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeActionPerformed
        // TODO add your handling code here:
        try {
            if(searchusertxt.getText().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
            }
                else{
                String sql;
                sql = "update userdata set state='Abnormal' where id= ?";//冻结用户
                pst3= con.prepareStatement(sql);
                pst3.setString(1,searchusertxt.getText());
                pst3.executeUpdate();//执行语句
                JOptionPane.showMessageDialog(this, "Execute Successfully!","Freeze",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminManageSystem_114.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_freezeActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
       cp.dispose();
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StatusReset;
    private javax.swing.JLabel change;
    private javax.swing.JLabel exit;
    private javax.swing.JButton freeze;
    private javax.swing.JLabel freeze_users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel searchuser;
    private javax.swing.JTextField searchusertxt;
    private javax.swing.JPanel thaw;
    private javax.swing.JButton thawExit;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
