/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 26625
 */
public class AdminManageUser_111 extends javax.swing.JFrame {

    /**
     * Creates new form AdminManageUser_111
     */
    String [] a;
    Statement stmt;
    Connection con;//连接数据库
    ResultSet rs;
    DefaultTableModel tm;
    PreparedStatement preparedStatement;
    public AdminManageUser_111() {
        initComponents();
        adduserpanel.setVisible(false);
        edituserpanel.setVisible(false);
        this.setDefaultCloseOperation(0x1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adduser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        top = new javax.swing.JLabel();
        adduserpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ok1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        tele = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        types = new javax.swing.JComboBox();
        password = new javax.swing.JPasswordField();
        edituserpanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        searchusertxt = new javax.swing.JTextField();
        searchbutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        cancel2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        edituser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        adduser.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        adduser.setText("Add User");
        adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adduserMouseClicked(evt);
            }
        });
        jPanel1.add(adduser);
        adduser.setBounds(80, 320, 100, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/HUNI.png"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 10, 150, 180);

        top.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        top.setText("User Management System");
        jPanel1.add(top);
        top.setBounds(430, 10, 312, 57);

        adduserpanel.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel5.setText("Add User");

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setText("UserType");

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setText("Tele");

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setText("UserName");

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setText("Password");

        ok1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        ok1.setText("OK");
        ok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok1MouseClicked(evt);
            }
        });
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        cancel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        types.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        types.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Administrator" }));

        javax.swing.GroupLayout adduserpanelLayout = new javax.swing.GroupLayout(adduserpanel);
        adduserpanel.setLayout(adduserpanelLayout);
        adduserpanelLayout.setHorizontalGroup(
            adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserpanelLayout.createSequentialGroup()
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adduserpanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adduserpanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(tele, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(types, 0, 276, Short.MAX_VALUE)
                            .addComponent(password))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        adduserpanelLayout.setVerticalGroup(
            adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(types, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adduserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(adduserpanel);
        adduserpanel.setBounds(280, 90, 510, 291);

        edituserpanel.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setText("User ID");

        searchusertxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/search2.png"))); // NOI18N
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
        });

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "UserNumber", "UserName", "Tele", "State", "Address", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usertable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(usertable);

        cancel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        cancel2.setText("OK");
        cancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel2MouseClicked(evt);
            }
        });
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage User");

        delete.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edituserpanelLayout = new javax.swing.GroupLayout(edituserpanel);
        edituserpanel.setLayout(edituserpanelLayout);
        edituserpanelLayout.setHorizontalGroup(
            edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edituserpanelLayout.createSequentialGroup()
                .addGroup(edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(edituserpanelLayout.createSequentialGroup()
                        .addGroup(edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(edituserpanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(searchusertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(edituserpanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(searchbutton)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edituserpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        edituserpanelLayout.setVerticalGroup(
            edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edituserpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchusertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(edituserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(edituserpanel);
        edituserpanel.setBounds(300, 100, 568, 277);

        edituser.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        edituser.setText("Manage User");
        edituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edituserMouseClicked(evt);
            }
        });
        jPanel1.add(edituser);
        edituser.setBounds(60, 260, 130, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(250, 70, 710, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(250, 0, 40, 590);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/背景（几何）1.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseClicked
        
        edituserpanel.setVisible(false);
        adduserpanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_adduserMouseClicked

    private void edituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseClicked
         adduserpanel.setVisible(false);
        edituserpanel.setVisible(true);
    }//GEN-LAST:event_edituserMouseClicked

    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
        // TODO add your handling code here:
        try{
                String sql;
                sql = "select * from userdata where id=?";
                con=DBClass.getConnection();
                PreparedStatement pst2 = con.prepareStatement(sql);
                pst2.setString(1, searchusertxt.getText());
                rs = pst2.executeQuery();//执行语句
                ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
		int ColumnCount = rsmd.getColumnCount();//获取表格列数
                tm = (DefaultTableModel)usertable.getModel();//建立表格模型，editbooktable表格变量名
                tm.setRowCount(0);//更新行数据，使表格清空
		while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
		{
                    for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                            {
                                a=new String[ColumnCount];//获取列头名字
                                for (int s =0; s < ColumnCount; s++)//小于行循环
                                {
					a[s]=rs.getString(s+1);//获取列数据
				}
                            }
			tm.addRow(a);//将行和列的数据整合，进行输出
			}
                        //当文本字段为空时弹出Warming窗口
                        if(searchusertxt.getText().length()==0)
                        {
                            JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                        }
                        tm.fireTableDataChanged();
		}
		catch (SQLException e) {
                   JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
                  }//数据库报错
                catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
                }//整体报错
    }//GEN-LAST:event_searchbuttonMouseClicked

    private void cancel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel2MouseClicked
        // TODO add your handling code here:
        adduserpanel.setVisible(false);
        edituserpanel.setVisible(false);
    }//GEN-LAST:event_cancel2MouseClicked

    private void ok1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok1MouseClicked
        // TODO add your handling code here:
        Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-zA-Z])(.{8,16})$");
        Matcher m1 = p.matcher(password.getText());
        
        Pattern p1 = Pattern.compile("^((13[0-9])|(15[^4])|(18[0-9])|(17[0-9])|(147))\\d{8}$");
        Matcher m2 = p1.matcher(tele.getText());
         String sql = null;
         if(username.getText().length()==0)
        {
             JOptionPane.showMessageDialog(this, "Empty user name!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(password.getText().length()==0)
        {
             JOptionPane.showMessageDialog(this, "Empty password!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(tele.getText().length()==0)
        {
             JOptionPane.showMessageDialog(this, "Empty Tele!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(m1.matches()==false){
                JOptionPane.showMessageDialog(this, "Please use both number and letters in password,length 8-16 ", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(m2.matches()==false){
                JOptionPane.showMessageDialog(this, " Please enter correct phonenumber ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
                String strr;
                    if(types.getSelectedIndex()==0)//user
                    {
                        sql = "insert into userdata(name,phonenumber,password) values ('"+username.getText()+"','"+tele.getText()+"','"+password.getText()+"');";
                        strr = "select id from userdata where name = ? and phonenumber = ? and password = ?";
                    }
                    else 
                    {
                        sql = "insert into admindata(name,phonenumber,password) values ('"+username.getText()+"','"+tele.getText()+"','"+password.getText()+"');";
                        strr = "select id from admindata where name = ? and phonenumber = ? and password = ?";
                    }
                    con = DBClass.getConnection();
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                    
                    con = DBClass.getConnection();
                    PreparedStatement pst = con.prepareStatement(strr);
                    pst.setString(1,username.getText());
                    pst.setString(2,tele.getText());
                    pst.setString(3,password.getText());
                    rs = pst.executeQuery();
                    rs.next();
            } catch (SQLException ex) {
                Logger.getLogger(AdminManageBooks_112.class.getName()).log(Level.SEVERE, null, ex);
            }
             try {
                 JOptionPane.showMessageDialog(this, "Add user successfully!UserID:"+rs.getString(1), "OK", JOptionPane.INFORMATION_MESSAGE);
             } catch (SQLException ex) {
                 Logger.getLogger(AdminManageUser_111.class.getName()).log(Level.SEVERE, null, ex);
             }
            this.dispose();
        }
        
    }//GEN-LAST:event_ok1MouseClicked

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel2ActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
    }//GEN-LAST:event_ok1ActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        con = DBClass.getConnection();
        String str = "delete from userdata where id = ?";
        try {
            con = DBClass.getConnection();
            PreparedStatement pst = con.prepareStatement(str);
            pst.setString(1, searchusertxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Executed successfully!", "Delete", JOptionPane.INFORMATION_MESSAGE);
            pst.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminManageUser_111.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adduser;
    private javax.swing.JPanel adduserpanel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JButton delete;
    private javax.swing.JLabel edituser;
    private javax.swing.JPanel edituserpanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton ok1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel searchbutton;
    private javax.swing.JTextField searchusertxt;
    private javax.swing.JTextField tele;
    private javax.swing.JLabel top;
    private javax.swing.JComboBox types;
    private javax.swing.JTextField username;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}