/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 26625
 */
public class AdminManageBooks_112 extends javax.swing.JFrame {

    /**
     * Creates new form AdminManageBooks_112
     */
    String [] a;
    Statement stmt;
    Connection con=DBClass.getConnection();//连接数据库
    ResultSet rs;
    DefaultTableModel tm;
    PreparedStatement preparedStatement;
    public AdminManageBooks_112() {
        initComponents();
        managebookpanel.setVisible(false);
        addbookpanel.setVisible(false);
        Books_on_loan.setVisible(false);
        this.setDefaultCloseOperation(0x1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        managebook = new javax.swing.JLabel();
        Books__on__loan = new javax.swing.JLabel();
        addbook = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        addbookpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        titletxt = new javax.swing.JTextField();
        authortxt = new javax.swing.JTextField();
        publicationdate = new javax.swing.JTextField();
        typebox = new javax.swing.JComboBox();
        addok = new javax.swing.JButton();
        addcancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        press = new javax.swing.JTextField();
        Books_on_loan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        booktable1 = new javax.swing.JScrollPane();
        booktable2 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        managebookpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        searchbooktxt = new javax.swing.JTextField();
        searchbutton = new javax.swing.JLabel();
        booktable = new javax.swing.JScrollPane();
        editbooktable = new javax.swing.JTable();
        deletebookbutton = new javax.swing.JButton();
        choice = new javax.swing.JComboBox();
        editcancel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        managebook.setBackground(new java.awt.Color(255, 255, 255));
        managebook.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        managebook.setText("Manage Book");
        managebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managebookMouseClicked(evt);
            }
        });
        jPanel1.add(managebook);
        managebook.setBounds(30, 250, 110, 38);

        Books__on__loan.setBackground(new java.awt.Color(255, 255, 255));
        Books__on__loan.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        Books__on__loan.setText("Books on loan");
        Books__on__loan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Books__on__loanMouseClicked(evt);
            }
        });
        jPanel1.add(Books__on__loan);
        Books__on__loan.setBounds(30, 300, 160, 50);

        addbook.setBackground(new java.awt.Color(255, 255, 255));
        addbook.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addbook.setText("Add Book");
        addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbookMouseClicked(evt);
            }
        });
        jPanel1.add(addbook);
        addbook.setBounds(30, 200, 79, 38);

        jLabel3.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel3.setText("Books Information Management");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 0, 610, 56);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/HUNI.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 10, 151, 176);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(230, 52, 820, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(230, 0, 30, 580);

        jPanel2.setOpaque(false);

        addbookpanel.setBackground(new java.awt.Color(255, 255, 255));
        addbookpanel.setOpaque(false);
        addbookpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("Add Book");
        addbookpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 100, 30));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Title");
        addbookpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 30));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Author");
        addbookpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 30));

        jLabel7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel7.setText("Publication Date");
        addbookpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 35));

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setText("Type");
        addbookpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 35));

        titletxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addbookpanel.add(titletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 551, 30));

        authortxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addbookpanel.add(authortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 551, 30));

        publicationdate.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addbookpanel.add(publicationdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 550, 35));

        typebox.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        typebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Textbook", "Science and Technology", "Literature book", "Military science book", "Agriculture science book" }));
        addbookpanel.add(typebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 156, 551, -1));

        addok.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addok.setText("OK");
        addok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addokMouseClicked(evt);
            }
        });
        addbookpanel.add(addok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 121, 41));

        addcancel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addcancel.setText("Cancel");
        addcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcancelActionPerformed(evt);
            }
        });
        addbookpanel.add(addcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 121, 41));

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setText("Press");
        addbookpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 35));

        press.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        addbookpanel.add(press, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 551, -1));

        Books_on_loan.setBackground(new java.awt.Color(255, 255, 255));
        Books_on_loan.setOpaque(false);
        Books_on_loan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setText("Books on loan");
        Books_on_loan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 150, 46));

        booktable2.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        booktable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Number", "Title", "Author", "Type", "Press", "publicationdate", "Borrowing_state", "Borrower_Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booktable2.getTableHeader().setReorderingAllowed(false);
        booktable1.setViewportView(booktable2);

        Books_on_loan.add(booktable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 290));

        back.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        Books_on_loan.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 46));

        managebookpanel.setBackground(new java.awt.Color(255, 255, 255));
        managebookpanel.setForeground(new java.awt.Color(255, 255, 255));
        managebookpanel.setOpaque(false);
        managebookpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setText("Manage Book");
        managebookpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 140, 34));

        searchbooktxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        managebookpanel.add(searchbooktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 378, 44));

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/search2.png"))); // NOI18N
        searchbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbuttonMouseClicked(evt);
            }
        });
        managebookpanel.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        editbooktable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        editbooktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Number", "Title", "Author", "Type", "Publication Date"
            }
        ));
        editbooktable.getTableHeader().setReorderingAllowed(false);
        booktable.setViewportView(editbooktable);

        managebookpanel.add(booktable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 520, 80));

        deletebookbutton.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        deletebookbutton.setText("Delete");
        deletebookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebookbuttonActionPerformed(evt);
            }
        });
        managebookpanel.add(deletebookbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 44));

        choice.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "BookID", "Author" }));
        managebookpanel.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 40));

        editcancel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        editcancel1.setText("Cancel");
        editcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcancel1ActionPerformed(evt);
            }
        });
        managebookpanel.add(editcancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 44));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addbookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Books_on_loan, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 50, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(managebookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Books_on_loan, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(managebookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(240, 60, 960, 406);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/背景（几何）1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebookbuttonActionPerformed
        try {
            // TODO add your handling code here:
            PreparedStatement pst;
            String str1=null;
            if(choice.getSelectedIndex()==0){
                str1 = "delete from bookdata where title = ?";
            }else if(choice.getSelectedIndex()==1){
                str1 = "delete from bookdata where id = ?";
            }else if(choice.getSelectedIndex()==2){
                str1 = "delete from bookdata where author = ?";
            }
            con=DBClass.getConnection();
            pst = con.prepareStatement(str1);
            pst.setString(1, searchbooktxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Executed Successfully!", "Delete", JOptionPane.INFORMATION_MESSAGE);
            pst.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminManageBooks_112.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deletebookbuttonActionPerformed

    private void searchbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbuttonMouseClicked
        // TODO add your handling code here:
        try{
            String sql;
            PreparedStatement pst;
            con=DBClass.getConnection();
            String str = this.searchbooktxt.getText();
            switch (choice.getSelectedIndex()) {
                case 0:
                    sql = "select * from bookdata where title=?";
                    break;
                case 1:
                    sql = "select * from bookdata where ID=?";
                    break;
                default:
                    sql = "select * from bookdata where author=?";
                    break;
            }
            pst = con.prepareStatement(sql);
            pst.setString(1,str);
            rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
            int ColumnCount = rsmd.getColumnCount();//获取表格列数
            tm = (DefaultTableModel) editbooktable.getModel();//建立表格模型，editbooktable表格变量名
            tm.setRowCount(0);//更新行数据，使表格清空
            while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
            {
                for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                    a=new String[ColumnCount];//获取列头名字
                    for (int s =0; s < ColumnCount; s++)//小于行循环
                    {
                        a[s]=rs.getString(s+1);//获取列数据
                    }
                }
                tm.addRow(a);//将行和列的数据整合，进行输出
            }
            
            
            //当文本字段为空时弹出Warming窗口
            if(searchbooktxt.getText().length()==0)
            {
                JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
            }
            tm.fireTableDataChanged();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
        }//数据库报错
        catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
        }//整体报错
    }//GEN-LAST:event_searchbuttonMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        managebookpanel.setVisible(false);
        addbookpanel.setVisible(false);
        Books_on_loan.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void addcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addcancelActionPerformed

        //add book-ADDButton
    private void addokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addokMouseClicked
        // TODO add your handling code here:

        String sql = null;
        if(titletxt.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Empty Title！", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(authortxt.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Empty Author!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(publicationdate.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Empty Publication Date!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(press.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Empty Press!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try {
                if(typebox.getSelectedIndex()==0)
                {
                    sql = "insert into bookdata(title,author,type,publishing_house,publicationdate) values ('"+titletxt.getText()+"','"+authortxt.getText()+"','Textbook','"+press.getText()+"','"+publicationdate.getText()+"');";
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                }
                else if(typebox.getSelectedIndex()==1)
                {
                    sql = "insert into bookdata(title,author,type,publishing_house,publicationdate) values ('"+titletxt.getText()+"','"+authortxt.getText()+"','Science&Technology','"+press.getText()+"','"+publicationdate.getText()+"');";
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                }
                else if(typebox.getSelectedIndex()==2)
                {
                    sql = "insert into bookdata(title,author,type,publishing_house,publicationdate) values ('"+titletxt.getText()+"','"+authortxt.getText()+"','Science&Technology','"+press.getText()+"','"+publicationdate.getText()+"');";
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                }
                else if(typebox.getSelectedIndex()==3)
                {
                    sql = "insert into bookdata(title,author,type,publishing_house,publicationdate) values ('"+titletxt.getText()+"','"+authortxt.getText()+"','Military science books','"+press.getText()+"','"+publicationdate.getText()+"');";
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                }
                else{
                    sql = "insert into bookdata(title,author,type,publishing_house,publicationdate) values ('"+titletxt.getText()+"','"+authortxt.getText()+"','Agriculturte science books','"+press.getText()+"','"+publicationdate.getText()+"');";
                    stmt = con.createStatement();//执行语句
                    stmt.executeUpdate(sql);//执行语句
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminManageBooks_112.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Add book successfully!", "OK", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_addokMouseClicked

    private void addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseClicked
        Books_on_loan.setVisible(false);
        managebookpanel.setVisible(false);
        addbookpanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addbookMouseClicked

    private void Books__on__loanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Books__on__loanMouseClicked
        // TODO add your handling code here:
        managebookpanel.setVisible(false);
        addbookpanel.setVisible(false);
        Books_on_loan.setVisible(true);
        try{
            String sql;
            con = DBClass.getConnection();
            //通过组合框进行选择
             sql = "select * from bookdata where book_borrowing_state ='Lent'";
            stmt = con.createStatement();//查询
            rs = stmt.executeQuery(sql);//执行语句
            ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
            int ColumnCount = rsmd.getColumnCount();//获取表格列数
            tm = (DefaultTableModel) booktable2.getModel();//建立表格模型，editbooktable表格变量名
            tm.setRowCount(0);//更新行数据，使表格清空
            while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
            {
                for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                    a=new String[ColumnCount];//获取列头名字
                    for (int s =0; s < ColumnCount; s++)//小于行循环
                    {
                        a[s]=rs.getString(s+1);//获取列数据
                    }
                }
                tm.addRow(a);//将行和列的数据整合，进行输出
            }
            tm.fireTableDataChanged();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
        }//数据库报错
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
        }//整体报错
    }//GEN-LAST:event_Books__on__loanMouseClicked

    private void managebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookMouseClicked
        addbookpanel.setVisible(false);
        Books_on_loan.setVisible(false);
        managebookpanel.setVisible(true);
    }//GEN-LAST:event_managebookMouseClicked

    private void editcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editcancel1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Books__on__loan;
    private javax.swing.JPanel Books_on_loan;
    private javax.swing.JLabel addbook;
    private javax.swing.JPanel addbookpanel;
    private javax.swing.JButton addcancel;
    private javax.swing.JButton addok;
    private javax.swing.JTextField authortxt;
    private javax.swing.JButton back;
    private javax.swing.JScrollPane booktable;
    private javax.swing.JScrollPane booktable1;
    private javax.swing.JTable booktable2;
    private javax.swing.JComboBox choice;
    private javax.swing.JButton deletebookbutton;
    private javax.swing.JTable editbooktable;
    private javax.swing.JButton editcancel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel managebook;
    private javax.swing.JPanel managebookpanel;
    private javax.swing.JTextField press;
    private javax.swing.JTextField publicationdate;
    private javax.swing.JTextField searchbooktxt;
    private javax.swing.JLabel searchbutton;
    private javax.swing.JTextField titletxt;
    private javax.swing.JComboBox typebox;
    // End of variables declaration//GEN-END:variables
}
