/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 123
 */
public class ChangeAddress_122 extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAddress
     */
    public ChangeAddress_122() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newaddress = new javax.swing.JTextArea();
        OKButon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Conform password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 99, -1, -1));
        jPanel1.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 101, 170, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("Enter new address:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 149, -1, -1));

        newaddress.setColumns(20);
        newaddress.setRows(5);
        jScrollPane1.setViewportView(newaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 149, 170, 89));

        OKButon.setText("OK");
        OKButon.setOpaque(false);
        OKButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButonActionPerformed(evt);
            }
        });
        jPanel1.add(OKButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 80, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Change Your Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 32, 306, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/背景（几何）1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButonActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst,pst1,pst2;
        ResultSet rs;
        String sql;
        boolean a;
        Connection con = DBClass.getConnection();
        String sql1 = "select * from userdata where id=? and password=?";
        try {
            pst = con.prepareStatement(sql1);
            pst.setString(1, LoginMenu_100.idinput.getText());
            pst.setString(2, confirmpassword.getText());
            rs = pst.executeQuery();//执行语句
            a = rs.next();
             if (confirmpassword.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Empty Password", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if(a == false){
                JOptionPane.showMessageDialog(this, "Wrong Password", "Warning", JOptionPane.WARNING_MESSAGE);
            }
             else if (a == true) {
                sql = "update userdata set address=? where id=?";
                pst1 = con.prepareStatement(sql);
                pst1.setString(1, newaddress.getText());
                pst1.setString(2, LoginMenu_100.idinput.getText());
                pst1.executeUpdate();//执行语句
                JOptionPane.showMessageDialog(this, "Address changed successfully!", "OK", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword_121.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_OKButonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButon;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea newaddress;
    // End of variables declaration//GEN-END:variables
}
