/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author 26625
 */
public class ChangePassword_121 extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword_121
     */
    Connection con=DBClass.getConnection();//连接数据库
    public ChangePassword_121() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        originalpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        new1 = new javax.swing.JPasswordField();
        new2 = new javax.swing.JPasswordField();
        uesrtype = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(165, 223, 224));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Original Password");

        userid.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("New Password");

        jLabel5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel5.setText("Uesr Type");

        originalpassword.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setText("New Password");

        new1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        new2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        uesrtype.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        uesrtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "User" }));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel4.setText("UserID");

        cancel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        ok.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        ok.setText("OK");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(111, 111, 111)
                        .addComponent(uesrtype, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(141, 141, 141)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(originalpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(81, 81, 81)
                        .addComponent(new1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81)
                        .addComponent(new2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(uesrtype, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(originalpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(new1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_okMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        PreparedStatement pst,pst1,pst2;
        ResultSet rs;
        String sql;
        //通过组合框进行选择
        if (uesrtype.getSelectedIndex() == 0)//Administrator
        {
            String sql1 = "select * from admindata where id=? and password=?";
            try {
                pst = con.prepareStatement(sql1);
                pst.setString(1, userid.getText());
                pst.setString(2, originalpassword.getText());//originalpassword是password
                rs = pst.executeQuery();//执行语句
                Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-zA-Z])(.{8,16})$");
                Matcher m1 = p.matcher(new1.getText());
                
                if (userid.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Empty UserID", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if (originalpassword.getPassword().length == 0) {
                    JOptionPane.showMessageDialog(this, "Empty OriginalPassword", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if(m1.matches()==false){
                    JOptionPane.showMessageDialog(this, "Please both number and lower letter in your password,length 8-16 ", "Error", JOptionPane.ERROR_MESSAGE);
            }
                
                else if (rs.next()) {
                    if (new1.getPassword().length == 0) {
                        JOptionPane.showMessageDialog(this, "Empty newpassword!", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else if (new2.getPassword().length == 0) {
                        JOptionPane.showMessageDialog(this, "Please enter your new password again!", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else if (Arrays.equals(new1.getPassword(), new2.getPassword())) {
                         sql = "update admindata set password=? where id=?";
                         pst1 = con.prepareStatement(sql);
                         pst1.setString(1, new2.getText());
                         pst1.setString(2, userid.getText());
                         pst1.executeUpdate();//执行语句
                         this.dispose();
                        JOptionPane.showMessageDialog(this, "Password changed successfully!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Please confirm that the passwords entered twice are the same!", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect UserID or Password", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword_121.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else//User
        {
            String sql2 = "select * from userdata where id=? and password=?";
            try {
                pst = con.prepareStatement(sql2);
                pst.setString(1, userid.getText());
                pst.setString(2, originalpassword.getText());//originalpassword是password
                rs = pst.executeQuery();//执行语句
                if (userid.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Empty UserID", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if (originalpassword.getPassword().length == 0) {
                    JOptionPane.showMessageDialog(this, "Empty OriginalPassword", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if (rs.next()) {
                    if (new1.getPassword().length == 0) {
                        JOptionPane.showMessageDialog(this, "Empty newpassword!", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else if (new2.getPassword().length == 0) {
                        JOptionPane.showMessageDialog(this, "Please enter your new password again!", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else if (Arrays.equals(new1.getPassword(), new2.getPassword())) //(new1.getPassword()).equals(new2.getPassword())
                    {
                         sql = "update userdata set password=? where id=?";
                         pst2 = con.prepareStatement(sql);
                         pst2.setString(1, new2.getText());
                         pst2.setString(2, userid.getText());
                         pst2.executeUpdate();//执行语句
                        JOptionPane.showMessageDialog(this, "Password changed successfully!", "OK", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Please confirm that the passwords entered twice are the same!", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect UserID or Password", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword_121.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField new1;
    private javax.swing.JPasswordField new2;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField originalpassword;
    private javax.swing.JComboBox uesrtype;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}