/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 26625
 */
public class LoginMenu_100 extends javax.swing.JFrame {

    /**
     * Creates new form LoginMenu_100
     */
    protected PreparedStatement pst;
    protected Connection con;
    protected String sql1 = null;
    String userstate;//定义用户状态变量
    protected ResultSet rs = null;
    protected static UserFounctionMenu_120 ufm = null;
    protected static AdminManageMenu_110 am = null;
    protected static RegistrationPage_130 rp = null;
    public LoginMenu_100() throws SQLException {
        con=DBClass.getConnection();
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newuser = new javax.swing.JLabel();
        UserType = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        passwordinput = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        idinput = new javax.swing.JTextField();
        usertype = new javax.swing.JComboBox();
        UserID = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newuser.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        newuser.setText("New User?");
        newuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserMouseClicked(evt);
            }
        });
        getContentPane().add(newuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 242, -1, -1));

        UserType.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        UserType.setText("UserType");
        getContentPane().add(UserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 73, -1, 31));

        Cancel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 235, 110, 36));

        Login.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 235, 110, 36));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordinputActionPerformed(evt);
            }
        });
        jPanel1.add(passwordinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 172, 166, -1));

        Password.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        Password.setText("Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 166, -1, 30));
        jPanel1.add(idinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 127, 166, -1));

        usertype.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        usertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Administrator" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 74, 166, -1));

        UserID.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        UserID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserID.setText("ID");
        jPanel1.add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 120, 80, 30));

        title.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Welcome To HNU Library System！");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, 361, 57));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/创造性的学校图书馆-荡桨在蓝色背景的白色空白的书-回到与拷贝空间的学校背景-121723381.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void newuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserMouseClicked
        try {
            // TODO add your handling code here:
            try {
                rp = new RegistrationPage_130();
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
            }
            rp.setLocationRelativeTo(null);
            rp.setVisible(true);
            rp.setDefaultCloseOperation(EXIT_ON_CLOSE);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newuserMouseClicked

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

        if(usertype.getSelectedIndex()==0){//User
            try {
                String str=null;
                str = "select * from userdata where id = ?";
                pst= con.prepareStatement(str);
                pst.setString(1,idinput.getText());
                rs = pst.executeQuery();
                rs.next();
                userstate = rs.getString(4);
                sql1 = "select 1 from userdata where id=? and password=?";
                if(userstate.equals("Normal"))
                {
                    try {
                        pst = con.prepareStatement(sql1);
                        pst.setString(1, idinput.getText());
                        pst.setString(2,passwordinput.getText());
                        rs = pst.executeQuery();
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        boolean a;
                        a=rs.next();
                        if(a){
                            ufm = new UserFounctionMenu_120();
                            ufm.setLocationRelativeTo(null);
                            ufm.setVisible(true);
                            this.dispose();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Wrong username or password", "Warning", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
               else{
                    JOptionPane.showMessageDialog(this, "Your ID's status is Abnormal,please connect with the administer!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
             } catch (SQLException ex) {
                Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
        else{//Administrator
            sql1 = "select 1 from admindata where id=? and password=?";
             try {
                pst = con.prepareStatement(sql1);
                pst.setString(1, idinput.getText());
                pst.setString(2,passwordinput.getText());
                rs = pst.executeQuery();
                } catch (SQLException ex) {
                Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
                }
             try {
                 boolean a;
                 a=rs.next();
                 if(a){
                    am = new AdminManageMenu_110();
                     am.setLocationRelativeTo(null);
                     am.setVisible(true);
                     this.dispose();
                 }
                 else{
                JOptionPane.showMessageDialog(this, "Wrong username or password", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                  } catch (SQLException ex) {
            Logger.getLogger(LoginMenu_100.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 }
    }//GEN-LAST:event_LoginActionPerformed

    private void passwordinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordinputActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel UserType;
    private javax.swing.JLabel background;
    protected static javax.swing.JTextField idinput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newuser;
    private javax.swing.JPasswordField passwordinput;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox usertype;
    // End of variables declaration//GEN-END:variables
}