/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author 123
 */
public class RegistrationPage_130 extends javax.swing.JFrame {
    
    public RegistrationPage_130() throws ClassNotFoundException, SQLException {

        con = DBClass.getConnection();
        if(con==null){
        System.out.println("Failed to connect;");
    }else{
            System.out.println("Successfully.");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Password1 = new javax.swing.JLabel();
        phonespace = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        passwordspace1 = new javax.swing.JPasswordField();
        notice2 = new javax.swing.JLabel();
        Password2 = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        passwordspace2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressspace = new javax.swing.JTextArea();
        usernamespace = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Picture = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 300));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel3.setLayout(null);

        Password1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password1.setText("Password");
        jPanel3.add(Password1);
        Password1.setBounds(250, 160, 90, 15);
        jPanel3.add(phonespace);
        phonespace.setBounds(360, 240, 150, 21);

        Phone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Phone.setText("Phone Number");
        jPanel3.add(Phone);
        Phone.setBounds(240, 240, 100, 15);

        UserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserName.setText("User Name");
        jPanel3.add(UserName);
        UserName.setBounds(260, 120, 80, 15);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel);
        cancel.setBounds(310, 390, 80, 23);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit);
        submit.setBounds(170, 390, 80, 23);

        passwordspace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordspace1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordspace1MouseExited(evt);
            }
        });
        jPanel3.add(passwordspace1);
        passwordspace1.setBounds(360, 160, 150, 21);

        notice2.setText("Both number and letters,length 8-16");
        jPanel3.add(notice2);
        notice2.setBounds(340, 180, 220, 20);

        Password2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password2.setText("Confirm Password");
        jPanel3.add(Password2);
        Password2.setBounds(230, 200, 110, 15);

        Address.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Address.setText("Address");
        jPanel3.add(Address);
        Address.setBounds(260, 280, 80, 15);

        passwordspace2.setAutoscrolls(false);
        jPanel3.add(passwordspace2);
        passwordspace2.setBounds(360, 200, 150, 21);

        addressspace.setColumns(20);
        addressspace.setRows(5);
        jScrollPane1.setViewportView(addressspace);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(360, 270, 150, 61);

        usernamespace.setToolTipText("");
        usernamespace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usernamespaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usernamespaceMouseExited(evt);
            }
        });
        usernamespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamespaceActionPerformed(evt);
            }
        });
        jPanel3.add(usernamespace);
        usernamespace.setBounds(360, 120, 150, 20);
        usernamespace.getAccessibleContext().setAccessibleName("");

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(50, 20, 450, 45);

        jPanel2.setOpaque(false);

        Picture.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/hnu130.jpg"))); // NOI18N
        Picture.setToolTipText("null");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Picture)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(18, 65, 210, 290);

        Title.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        Title.setText("User Registration");
        jPanel3.add(Title);
        Title.setBounds(80, 40, 408, 45);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/pbqe4xb5ptf.jpg"))); // NOI18N
        jPanel3.add(background);
        background.setBounds(0, -10, 580, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Main.lm.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        DBClass.getConnection();
        try {
            sql1=usernamespace.getText();
            sql2=passwordspace1.getText();
            sql3=phonespace.getText();
            sql4=addressspace.getText();
            sql = "insert into userdata(name,password,phonenumber,address) values (?,?,?,?)"; 
            Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-zA-Z])(.{8,16})$");
            Pattern p1 = Pattern.compile("^((13[0-9])|(15[^4])|(18[0-9])|(17[0-9])|(147))\\d{8}$");
        Matcher m1 = p.matcher(passwordspace1.getText());
        Matcher m2 = p1.matcher(phonespace.getText());
            //用户名为空，报错
            if (usernamespace.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Empty User Name", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            //密码为空，报错
            else if (passwordspace1.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Empty Password", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            //密码为空，报错
            else if (passwordspace2.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Please Confirm your password", "Warning", JOptionPane.WARNING_MESSAGE);
            }else if(m1.matches()==false){
                JOptionPane.showMessageDialog(this, "Please use both number and letter in your password,length 8-16 ", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(m2.matches()==false){
                JOptionPane.showMessageDialog(this, "Please enter the right phone number", "Error", JOptionPane.ERROR_MESSAGE);
            }
            //两次密码一致，欢迎界面弹出
            else if (Arrays.equals(passwordspace1.getPassword(), passwordspace2.getPassword())) {
                pst = con.prepareStatement(sql);
                pst.setString(1,usernamespace.getText());
                pst.setString(2,passwordspace1.getText());
                pst.setString(3,phonespace.getText());
                pst.setString(4,addressspace.getText());
                pst.executeUpdate();
                Welcome_131 w = new Welcome_131();
                w.setLocationRelativeTo(null);
                w.setVisible(true);
                this.dispose();
            } 
            else {
                JOptionPane.showMessageDialog(this, "Please Enter your password again", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationPage_130.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void usernamespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamespaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamespaceActionPerformed

    private void usernamespaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernamespaceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamespaceMouseEntered

    private void usernamespaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernamespaceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamespaceMouseExited

    private void passwordspace1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordspace1MouseEntered
        // TODO add your handling code here:
        if(evt.getSource()==passwordspace1)
        {
            notice2.setVisible(true);
        }
        
    }//GEN-LAST:event_passwordspace1MouseEntered

    private void passwordspace1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordspace1MouseExited
        // TODO add your handling code here:
          if(evt.getSource()==passwordspace1)
        {
            notice2.setVisible(false);
        }
    }//GEN-LAST:event_passwordspace1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Password1;
    private javax.swing.JLabel Password2;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Picture;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UserName;
    protected static javax.swing.JTextArea addressspace;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel notice2;
    protected static javax.swing.JPasswordField passwordspace1;
    private javax.swing.JPasswordField passwordspace2;
    protected static javax.swing.JTextField phonespace;
    private javax.swing.JButton submit;
    protected static javax.swing.JTextField usernamespace;
    // End of variables declaration//GEN-END:variables

    String sql;
    String sql1;
    String sql2;
    String sql3;
    String sql4;
    String p2 = "^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,20}$";
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    Connection con = null;
}
