/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Librarymanagement;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 26625
 */
public class UserFounctionMenu_120 extends javax.swing.JFrame {
  /**
     * Creates new form AdminManageBooks_112
     */
//    
//    Locale l=new Locale("zh", "CN");
    String [] a;
    String str,usrnm;
    Statement stmt;
    Connection con=DBClass.getConnection();//连接数据库
    ResultSet rs,rs1;
    DefaultTableModel tm;
    PreparedStatement preparedStatement;
    protected  ChangeUserName_123 cun;
    protected  ChangeAddress_122 cad;
    protected ChangePhoneNumber_124 cpn;
    
    public UserFounctionMenu_120() throws SQLException {
        
        
        str = "select * from userdata where id = ?";
        preparedStatement = con.prepareStatement(str);
        preparedStatement.setString(1,LoginMenu_100.idinput.getText());
        rs1 = preparedStatement.executeQuery();
        rs1.next();
        usrnm = rs1.getString(2);
        initComponents();
        
        
        personaldetails.setVisible(false);
        bibliographicretrieval.setVisible(false);
        borrowingstatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changeinformation = new javax.swing.JLabel();
        bibliographicretrievallabel = new javax.swing.JLabel();
        borrowingstatelabel = new javax.swing.JLabel();
        personaldetails = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        changeinformationtable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        bibliographicretrieval = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchbook = new javax.swing.JLabel();
        searchtype1 = new javax.swing.JComboBox();
        booktable2 = new javax.swing.JScrollPane();
        searchbooktable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        borrowbook = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        borrowingstatus = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        booktable1 = new javax.swing.JScrollPane();
        loantable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        changename = new javax.swing.JLabel();
        changeaddress = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        change_ph_number = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(165, 223, 224));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Libraryphoto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel1.setText("Hainan University Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/profilephoto.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 112, 107));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel4.setText("UserName");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel5.setText("UserID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setText("Personal Information");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 145, -1, -1));

        changeinformation.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        changeinformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeinformation.setText("Personal Information");
        changeinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeinformationMouseClicked(evt);
            }
        });
        jPanel1.add(changeinformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 288, -1, -1));

        bibliographicretrievallabel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        bibliographicretrievallabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bibliographicretrievallabel.setText("Book Search");
        bibliographicretrievallabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bibliographicretrievallabelMouseClicked(evt);
            }
        });
        jPanel1.add(bibliographicretrievallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 330, 200, 39));

        borrowingstatelabel.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        borrowingstatelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowingstatelabel.setText("Borrowing status");
        borrowingstatelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowingstatelabelMouseClicked(evt);
            }
        });
        jPanel1.add(borrowingstatelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 200, 39));

        personaldetails.setBackground(new java.awt.Color(255, 255, 255));
        personaldetails.setOpaque(false);
        personaldetails.setPreferredSize(new java.awt.Dimension(300, 300));
        personaldetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Personal Information");
        personaldetails.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, -1));

        changeinformationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "UserName", "Tele", "State", "Address", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        changeinformationtable.setToolTipText("");
        jScrollPane1.setViewportView(changeinformationtable);

        personaldetails.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 60));

        jPanel1.add(personaldetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 650, 186));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 115, 564, 11));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 6, 760));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, 339, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 117, 86, 10));

        bibliographicretrieval.setOpaque(false);
        bibliographicretrieval.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel7.setText("Books search");
        bibliographicretrieval.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 0, 129, 30));

        searchtxt.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        bibliographicretrieval.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 258, 45));

        searchbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/search2.png"))); // NOI18N
        searchbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbookMouseClicked(evt);
            }
        });
        bibliographicretrieval.add(searchbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 49, -1, 45));

        searchtype1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        searchtype1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "BookID", "Author" }));
        searchtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtype1ActionPerformed(evt);
            }
        });
        bibliographicretrieval.add(searchtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 170, 45));

        searchbooktable.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        searchbooktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Title", "Author", "Type"
            }
        ));
        booktable2.setViewportView(searchbooktable);

        bibliographicretrieval.add(booktable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 506, 60));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("You can borrow or return a book through searching BookID");
        bibliographicretrieval.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 500, -1));

        borrowbook.setText("Borrow");
        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        bibliographicretrieval.add(borrowbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        returnbook.setText("Return");
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        bibliographicretrieval.add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jPanel1.add(bibliographicretrieval, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 670, 240));

        borrowingstatus.setBackground(new java.awt.Color(255, 255, 255));
        borrowingstatus.setOpaque(false);
        borrowingstatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setText("Books on Loan");
        borrowingstatus.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 10, 142, 34));

        loantable.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        loantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Number", "Title", "Author", "Type"
            }
        ));
        booktable1.setViewportView(loantable);

        borrowingstatus.add(booktable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 506, 90));

        jPanel1.add(borrowingstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Change Password");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 200, 40));

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setText(LoginMenu_100.idinput.getText());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, -1));

        jLabel11.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel11.setText(usrnm);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 120, -1));

        changename.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        changename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changename.setText("Change UserName");
        changename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changenameMouseClicked(evt);
            }
        });
        jPanel1.add(changename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 200, -1));

        changeaddress.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        changeaddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeaddress.setText("Change Address");
        changeaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeaddressMouseClicked(evt);
            }
        });
        jPanel1.add(changeaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, -1));

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("EXIT");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 200, -1));

        change_ph_number.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        change_ph_number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        change_ph_number.setText("Change Phonenumber");
        change_ph_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_ph_numberMouseClicked(evt);
            }
        });
        jPanel1.add(change_ph_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 220, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeinformationMouseClicked
      //在弹出的panel里面的表格中直接显示用户信息，并点击ok完成修改
        bibliographicretrieval.setVisible(false);
      borrowingstatus.setVisible(false);
      personaldetails.setVisible(true);
      try{    
                String sql = "select * from userdata where id= '"+LoginMenu_100.idinput.getText()+"'";
                stmt = con.createStatement();//查询
		rs = stmt.executeQuery(sql);//执行语句
                ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
		int ColumnCount = rsmd.getColumnCount();//获取表格列数
                tm = (DefaultTableModel) changeinformationtable.getModel();//建立表格模型，editbooktable表格变量名
                tm.setRowCount(0);//更新行数据，使表格清空
		while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
		{
                    for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                            {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                                a=new String[ColumnCount];//获取列头名字
                                for (int s =0; s < ColumnCount; s++)//小于行循环
                                {
					a[s]=rs.getString(s+1);//获取列数据
				}
                            }
			tm.addRow(a);//将行和列的数据整合，进行输出
			}
                        tm.fireTableDataChanged();
//                        rs.close();
//                        stmt.close();
//                        con.close();//关闭
		}
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
                }//数据库报错
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
                }//整体报错
    }//GEN-LAST:event_changeinformationMouseClicked

    private void bibliographicretrievallabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliographicretrievallabelMouseClicked
        
        personaldetails.setVisible(false);
        borrowingstatus.setVisible(false);
        bibliographicretrieval.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bibliographicretrievallabelMouseClicked

    private void borrowingstatelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingstatelabelMouseClicked
//显示在用户名下借出的书籍
        personaldetails.setVisible(false);
        bibliographicretrieval.setVisible(false);
        borrowingstatus.setVisible(true);
        try{    
                String sql = "select * from bookdata where borrower_id= '"+LoginMenu_100.idinput.getText()+"'";
                stmt = con.createStatement();//查询
		rs = stmt.executeQuery(sql);//执行语句
                ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
		int ColumnCount = rsmd.getColumnCount();//获取表格列数
                tm = (DefaultTableModel) loantable.getModel();//建立表格模型，editbooktable表格变量名
                tm.setRowCount(0);//更新行数据，使表格清空
		while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
		{
                    for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                            {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                                a=new String[ColumnCount];//获取列头名字
                                for (int s =0; s < ColumnCount; s++)//小于行循环
                                {
					a[s]=rs.getString(s+1);//获取列数据
				}
                            }
			tm.addRow(a);//将行和列的数据整合，进行输出
			}
                        tm.fireTableDataChanged();
		}
		catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
                }//数据库报错
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
                }//整体报错
    }//GEN-LAST:event_borrowingstatelabelMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        ChangePassword_121 cp =new ChangePassword_121();
                cp.setLocationRelativeTo(null);
                cp.setDefaultCloseOperation(HIDE_ON_CLOSE);
                cp.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void searchbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbookMouseClicked
        // TODO add your handling code here:
        try{    
                String sql;
                PreparedStatement pst;
                String str=this.searchtxt.getText();
                //通过组合框进行选择
                if(searchtype1.getSelectedIndex()==0){
                    sql = "select * from bookdata where title=?";
                }
                else if(searchtype1.getSelectedIndex()==1){
                    sql = "select * from bookdata where ID=?";
                }
                else{
                    sql = "select * from bookdata where author=?";
                }
                pst = con.prepareStatement(sql);//查询
                pst.setString(1, str);
		rs = pst.executeQuery();//执行语句
                ResultSetMetaData rsmd = rs.getMetaData();//获取原数据，数据的数据，比如行数列数，列名
		int ColumnCount = rsmd.getColumnCount();//获取表格列数
                tm = (DefaultTableModel) searchbooktable.getModel();//建立表格模型，editbooktable表格变量名
                tm.setRowCount(0);//更新行数据，使表格清空
		while (rs.next())//结果不为空，执行，以行进行循环，一次提取一条结果
		{
                    for (int i = 1; i <= ColumnCount; i++)//小于列数循环
                            {  // tm.addColumn(rsmd.getColumnName(i));//添加列头
                                a=new String[ColumnCount];//获取列头名字
                                for (int s =0; s < ColumnCount; s++)//小于行循环
                                {
					a[s]=rs.getString(s+1);//获取列数据
				}
                            }
			tm.addRow(a);//将行和列的数据整合，进行输出
			}
                        //当文本字段为空时弹出Warning窗口
                        if(searchtxt.getText().length()==0)
                        {
                            JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                        }
                        tm.fireTableDataChanged();
//                        rs.close();
//                        stmt.close();
//                        con.close();//关闭
		}
		catch (SQLException e) {
                   JOptionPane.showMessageDialog(this, e, e.getMessage(), WIDTH, null);
                  }//数据库报错
                catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
                }//整体报错
    }//GEN-LAST:event_searchbookMouseClicked

    private void changenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changenameMouseClicked
        // TODO add your handling code here:
        cun = new ChangeUserName_123();
        cun.setLocationRelativeTo(null);
        cun.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cun.setVisible(true);
    }//GEN-LAST:event_changenameMouseClicked

    private void changeaddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeaddressMouseClicked
        // TODO add your handling code here:
        cad = new ChangeAddress_122();
        cad.setLocationRelativeTo(null);
        cad.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cad.setVisible(true);
    }//GEN-LAST:event_changeaddressMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void change_ph_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_ph_numberMouseClicked
        // TODO add your handling code here:
        cpn = new ChangePhoneNumber_124();
        cpn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cpn.setLocationRelativeTo(null);
        cpn.setVisible(true);
    }//GEN-LAST:event_change_ph_numberMouseClicked

    private void searchtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtype1ActionPerformed

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
        // TODO add your handling code here:
        if(searchtype1.getSelectedIndex()!=1){
            JOptionPane.showMessageDialog(this, "Searching through BookID to borrow books!","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                con = DBClass.getConnection();
                
                String str = "select * from bookdata where id = ?";
                PreparedStatement pst = con.prepareStatement(str);
                pst.setString(1, searchtxt.getText());
                ResultSet rs = pst.executeQuery();
                boolean book = rs.next();
                if(searchtxt.getText().length() == 0){
                    JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                }else if(book == false){
                    JOptionPane.showMessageDialog(this, "No such book!","Warning",JOptionPane.WARNING_MESSAGE);
                }else if("Lent".equalsIgnoreCase(rs.getString(7))){
                    JOptionPane.showMessageDialog(this, "The book has been lent!","Warning",JOptionPane.WARNING_MESSAGE);
                }else{
                    String str1 = "update bookdata set book_borrowing_state = 'Lent' where id = ?; ";
                    String str2 = "update bookdata set borrower_id = ? where id = ?";
                    pst = con.prepareStatement(str1);
                    pst.setString(1, searchtxt.getText());
                    pst.executeUpdate();//执行了第一条语句str1，更新图书状态
                    
                    //创建Borrow触发器
                String trg = "create trigger trg_borrow after update on bookdata\n" +
                    "for each row\n" +
                    "begin \n" +
                    "insert into bookreport values(old.id,old.title,'Borrowed',new.borrower_id,now());\n" +
                    "end;";
                Statement stmt1 = con.createStatement();
                stmt1.execute(trg);
                    
                    pst = con.prepareStatement(str2);
                    pst.setString(1, LoginMenu_100.idinput.getText());
                    pst.setString(2, searchtxt.getText());
                    pst.executeUpdate();//执行了第二条语句str2，更新borrower_id
                    JOptionPane.showMessageDialog(this, "Borrowed Successfully!","Borrow",JOptionPane.INFORMATION_MESSAGE);
                    
                    //删除触发器
                    String deltrg = "drop trigger trg_borrow";
                Statement delstmt = con.createStatement();
                delstmt.execute(deltrg);
                delstmt.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(UserFounctionMenu_120.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_borrowbookActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
        // TODO add your handling code here:
        if(searchtype1.getSelectedIndex()!=1){
            JOptionPane.showMessageDialog(this, "Searching through BookID to return books!","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                con = DBClass.getConnection();

                String str = "select * from bookdata where id = ?";
                PreparedStatement pst = con.prepareStatement(str);
                pst.setString(1, searchtxt.getText());
                ResultSet rs = pst.executeQuery();
                if(searchtxt.getText().length() == 0){
                    JOptionPane.showMessageDialog(this, "Empty!","Warning",JOptionPane.WARNING_MESSAGE);
                }else if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "No such book!","Warning",JOptionPane.WARNING_MESSAGE);
                }else if("Not Lent".equalsIgnoreCase(rs.getString(7))){
                    JOptionPane.showMessageDialog(this, "You have not borrowed this book!","Warning",JOptionPane.WARNING_MESSAGE);
                }else{
                    String str1 = "update bookdata set book_borrowing_state = 'Not lent' where id = ?; ";
                    String str2 = "update bookdata set borrower_id = null where id = ?";
                    pst = con.prepareStatement(str1);
                    pst.setString(1, searchtxt.getText());
                    pst.executeUpdate();//执行了第一条语句str1，更新图书状态
                    
                    //创建触发器
                String trg = "create trigger trg_return after update on bookdata\n" +
                    "for each row\n" +
                    "begin \n" +
                    "insert into bookreport values(old.id,old.title,'Returned',old.borrower_id,now());\n" +
                    "end;";
                Statement stmt1 = con.createStatement();
                stmt1.execute(trg);
                    
                    pst = con.prepareStatement(str2);
                    pst.setString(1, searchtxt.getText());
                    pst.executeUpdate();//执行了第二条语句str2，更新borrower_id
                    JOptionPane.showMessageDialog(this, "Returned Successfully!","Return",JOptionPane.INFORMATION_MESSAGE);
                    //删除触发器
                    String deltrg = "drop trigger trg_return";
//                    String deltrgbook = "drop trigger trg_book";
                    Statement delstmt = con.createStatement();
                    delstmt.execute(deltrg);
                    delstmt.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(UserFounctionMenu_120.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_returnbookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bibliographicretrieval;
    private javax.swing.JLabel bibliographicretrievallabel;
    private javax.swing.JScrollPane booktable1;
    private javax.swing.JScrollPane booktable2;
    private javax.swing.JButton borrowbook;
    private javax.swing.JLabel borrowingstatelabel;
    private javax.swing.JPanel borrowingstatus;
    private javax.swing.JLabel change_ph_number;
    private javax.swing.JLabel changeaddress;
    private javax.swing.JLabel changeinformation;
    private javax.swing.JTable changeinformationtable;
    private javax.swing.JLabel changename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable loantable;
    private javax.swing.JPanel personaldetails;
    private javax.swing.JButton returnbook;
    private javax.swing.JLabel searchbook;
    private javax.swing.JTable searchbooktable;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JComboBox searchtype1;
    // End of variables declaration//GEN-END:variables
}
